"""
execution_agent.py

Purpose:
Executes SQL queries generated by BI Navigator.
"""

from services.query_service import QueryService


class ExecutionAgent:

    def __init__(self):

        self.query_service = QueryService()

    def execute(self, sql: str):

        try:

            columns, rows = self.query_service.execute_query(sql)

            return {
                "success": True,
                "columns": columns,
                "rows": rows,
                "row_count": len(rows)
            }

        except Exception as error:

            return {
                "success": False,
                "error": str(error)
            }